apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oqxy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-oqxy@sha256:2dd0fdaf7bd6d42b67dcd911c2414dff9f2392f7670fb30dadc7a9b5dd0cdc37
        name: my-nodejs
        resources: {}
status: {}
